[assembly: ThemeInfo(ResourceDictionaryLocation.None, ResourceDictionaryLocation.SourceAssembly)]
[assembly: InternalsVisibleTo("BgCommon.Prism.Wpf")]
[assembly: InternalsVisibleTo("BgControls")]
[assembly: XmlnsDefinition("http://www.sz-baigu.com/", "BgCommon.Localization")]
[assembly: XmlnsDefinition("http://www.sz-baigu.com/", "BgCommon.Localization.Attributes")]
[assembly: XmlnsDefinition("http://www.sz-baigu.com/", "BgCommon.Localization.ComponentModel")]
[assembly: XmlnsDefinition("http://www.sz-baigu.com/", "BgCommon.Localization.Converters")]
[assembly: XmlnsDefinition("http://www.sz-baigu.com/", "BgCommon.Localization.IO")]
[assembly: XmlnsDefinition("http://www.sz-baigu.com/", "BgCommon.Localization.Json.Converters")]
[assembly: XmlnsDefinition("http://www.sz-baigu.com/", "BgCommon.Localization.Json.Models")]
[assembly: XmlnsDefinition("http://www.sz-baigu.com/", "BgCommon.Localization.Json.Models.v1")]
[assembly: XmlnsPrefix("http://www.sz-baigu.com/", "bg")]